language: python

python:
  - 2.6
  - 2.7

before_install:
  - sudo apt-get install freetds-dev
  - pip install --use-mirrors Cython nose

install:
  - python setup.py install

script:
  - nosetests -v tests/test_config.py tests/test_utils.py
